version: "3"
services:

  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      discovery.type: single-node
#    volumes:
#      - ./docker/elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"